-- +goose Up
-- +goose StatementBegin
create table if not exists users
(
    id       integer generated by default as identity primary key,
    tg_id    integer not null,
    name     text    not null
        constraint users_name_check
            check (name <> ''::text),
    currency text    not null,
    limits   integer not null
);

comment on table users is 'Пользователи ТГ';

-- Индекс по ТГ-идентификатору пользователя для ускорения поиска.
create unique index if not exists users_tg_id
    on users (tg_id);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop index users_tg_id;
DROP TABLE IF EXISTS "user";
-- +goose StatementEnd