// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: report.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserReportsReciverClient is the client API for UserReportsReciver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserReportsReciverClient interface {
	PutReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
}

type userReportsReciverClient struct {
	cc grpc.ClientConnInterface
}

func NewUserReportsReciverClient(cc grpc.ClientConnInterface) UserReportsReciverClient {
	return &userReportsReciverClient{cc}
}

func (c *userReportsReciverClient) PutReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, "/report.UserReportsReciver/PutReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserReportsReciverServer is the server API for UserReportsReciver service.
// All implementations must embed UnimplementedUserReportsReciverServer
// for forward compatibility
type UserReportsReciverServer interface {
	PutReport(context.Context, *ReportRequest) (*ReportResponse, error)
	mustEmbedUnimplementedUserReportsReciverServer()
}

// UnimplementedUserReportsReciverServer must be embedded to have forward compatible implementations.
type UnimplementedUserReportsReciverServer struct {
}

func (UnimplementedUserReportsReciverServer) PutReport(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutReport not implemented")
}
func (UnimplementedUserReportsReciverServer) mustEmbedUnimplementedUserReportsReciverServer() {}

// UnsafeUserReportsReciverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserReportsReciverServer will
// result in compilation errors.
type UnsafeUserReportsReciverServer interface {
	mustEmbedUnimplementedUserReportsReciverServer()
}

func RegisterUserReportsReciverServer(s grpc.ServiceRegistrar, srv UserReportsReciverServer) {
	s.RegisterService(&UserReportsReciver_ServiceDesc, srv)
}

func _UserReportsReciver_PutReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserReportsReciverServer).PutReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.UserReportsReciver/PutReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserReportsReciverServer).PutReport(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserReportsReciver_ServiceDesc is the grpc.ServiceDesc for UserReportsReciver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserReportsReciver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "report.UserReportsReciver",
	HandlerType: (*UserReportsReciverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutReport",
			Handler:    _UserReportsReciver_PutReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report.proto",
}
